### ISSUE TITLE
GOOD FEEDBACK

### ISSUE THREAD

**Issue by yde13** [xavizus/nackademin-todo-app#1]
SNyggt att du skapar test-data i en annan fil ! 🥇  :)

https://github.com/xavizus/nackademin-todo-app/blob/b0a58805044afed0e64d653ee5e47042c275f02f/tests/testTasksToAdd.js#L56

**Comment by xavizus** [comment]
Tack så mycket! Uppskattar feedbacken väldigt mycket!
