### ISSUE TITLE
Mer tester, annars snygg och läsbar kod

### ISSUE THREAD

**Issue by ztreg** [xavizus/nackademin-todo-app#3]
Skulle rekommendera att göra flera tester och vara mer nogrann med testbeskrivning
https://github.com/xavizus/nackademin-todo-app/blob/b0a58805044afed0e64d653ee5e47042c275f02f/tests/api_unit_test.js#L37
Är ett exempel, men hittade bara ett så bra jobbat!

//Mvh Jonas

**Comment by xavizus** [comment]
Jag har nu lagt till mer tester och mer noggrann beskrivning.
