### ISSUE TITLE
Väldigt bra ide som jag kommer sno!

### ISSUE THREAD

**Issue by ztreg** [xavizus/nackademin-todo-app#4]
https://github.com/xavizus/nackademin-todo-app/blob/b0a58805044afed0e64d653ee5e47042c275f02f/tests/api_integration_test.js#L13

Väldigt kort och snyggt sätt att lägga till data med en importerad mochup fil!

**Comment by xavizus** [comment]
Roligt att ens kod har hjälpt dig!
